[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=index.theme
Type=X-GNOME-Metatheme
Comment=
Name[es_AR]=index.theme

[X-GNOME-Metatheme]
GtkTheme=vamox-celeste
MetacityTheme=vamox-celeste
IconTheme=vamox-celeste
GtkColorScheme=fg_color:#54a554a554a5,bg_color:#f0f0f0f0f0f0,text_color:#383838383838,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#8d8dadadcccc,tooltip_fg_color:#383838383838,tooltip_bg_color:#f5f5f5f5b5b5
CursorTheme=Human
CursorSize=18
